"""

2. DOCKERFILE : PRODUCER (Le Générateur Python)
--------------------------------------------------------------------------------
RÔLE : Faire tourner ton script producer.py en continu.
IMAGE DE BASE : python:3.9-slim
ACTIONS :
   [ ] Créer un dossier /app dans le conteneur
   [ ] Copier 'requirements.txt' (contenant kafka-python et faker)
   [ ] Lancer 'pip install'
   [ ] Copier 'producer.py'
   [ ] COMMANDE : python producer.py
     
"""
