"""
3. DOCKERFILE : PYSPARK (Le Consommateur/Analyseur)
--------------------------------------------------------------------------------
RÔLE : Créer l'environnement Big Data pour Spark.
IMAGE DE BASE : bitnami/spark:latest (très pratique car tout est pré-installé)
ACTIONS :
   [ ] Installer les dépendances Python (pyspark)
   [ ] Télécharger le connecteur JAR (spark-sql-kafka)
   [ ] Copier 'pyspark_consumer.py'
   [ ] COMMANDE : spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.x.x pyspark_consumer.py
================================================================================
"""