"""
================================================================================
PROJET INDUTECH - ARCHITECTURE DES DOCKERFILES
================================================================================

1. DOCKERFILE : REDPANDA (Le Broker)
--------------------------------------------------------------------------------
RÔLE : Créer le serveur de streaming.
IMAGE DE BASE : docker.redpanda.com/redpandadata/redpanda:latest
ACTIONS : 
   [ ] Exposer les ports (9092 pour Kafka, 8081 pour Schema Registry)
   [ ] Configurer le mode "dev-container" pour un démarrage rapide
   [ ] (Optionnel) Créer automatiquement le topic 'client_tickets' au démarrage



"""